sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNwFH8vWaf6hcE9CZxz
    access-key-secret: bA9AWmBIsGvzU2WUWCeF48nnokckAF
    bucket-name: pinkle
  redis:
    host: localhost
    port: 6379
    database: 0
    password: